/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    orders: Order;
    coupons: Coupon;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'site-settings': SiteSetting;
    home: Home;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  description?: string | null;
  slug: string;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  price: number;
  /**
   * Price before discount for showing savings
   */
  compareAtPrice?: number | null;
  slug: string;
  category: number | Category;
  images: {
    image: number | Media;
    id?: string | null;
  }[];
  productType: 'simple' | 'variable';
  variants?:
    | {
        /**
         * e.g., "Red - Large", "Blue - Medium"
         */
        name: string;
        /**
         * Color name or hex code
         */
        color?: string | null;
        size?: ('xs' | 's' | 'm' | 'l' | 'xl' | 'xxl') | null;
        sku: string;
        price: number;
        stock: number;
        /**
         * Specific image for this variant (optional)
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Stock quantity for simple products
   */
  simpleStock?: number | null;
  sku?: string | null;
  featured?: boolean | null;
  status: 'active' | 'inactive' | 'out_of_stock';
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  customer: {
    email: string;
    firstName: string;
    lastName: string;
    phone?: string | null;
  };
  shippingAddress: {
    street: string;
    city: string;
    state: string;
    zipCode: string;
    country: string;
  };
  billingAddress?: {
    sameAsShipping?: boolean | null;
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zipCode?: string | null;
    country?: string | null;
  };
  items: {
    product: number | Product;
    /**
     * Variant identifier (e.g., "red-large")
     */
    variant?: string | null;
    quantity: number;
    /**
     * Price at time of purchase
     */
    price: number;
    /**
     * quantity × price
     */
    total: number;
    id?: string | null;
  }[];
  subtotal: number;
  coupon?: {
    /**
     * Applied coupon code
     */
    code?: string | null;
    discountType?: ('percentage' | 'fixed' | 'free_shipping') | null;
    /**
     * Applied discount value
     */
    discountValue?: number | null;
    /**
     * Total discounted amount
     */
    discountAmount?: number | null;
  };
  shipping: number;
  tax: number;
  total: number;
  status: 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  paymentStatus: 'pending' | 'paid' | 'failed' | 'refunded';
  paymentMethod?: ('mercado_pago' | 'transfer' | 'cod') | null;
  /**
   * Internal notes about the order
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  /**
   * Coupon code (e.g.: WELCOME15, FREESHIPPING)
   */
  code: string;
  /**
   * Coupon description to display to the user
   */
  description: string;
  discountType: 'percentage' | 'fixed' | 'free_shipping';
  /**
   * Discount value (percentage or amount in pesos)
   */
  discountValue?: number | null;
  /**
   * Minimum purchase amount to apply the coupon (optional)
   */
  minimumPurchase?: number | null;
  /**
   * Maximum number of times the coupon can be used (leave empty for unlimited)
   */
  usageLimit?: number | null;
  /**
   * Number of times the coupon has been used
   */
  usageCount?: number | null;
  /**
   * Date from which the coupon is valid
   */
  validFrom: string;
  /**
   * Date until which the coupon is valid (optional)
   */
  validUntil?: string | null;
  /**
   * Whether the coupon is active and can be used
   */
  active?: boolean | null;
  /**
   * Display this coupon on the public site
   */
  showOnSite?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  slug?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  price?: T;
  compareAtPrice?: T;
  slug?: T;
  category?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  productType?: T;
  variants?:
    | T
    | {
        name?: T;
        color?: T;
        size?: T;
        sku?: T;
        price?: T;
        stock?: T;
        image?: T;
        id?: T;
      };
  simpleStock?: T;
  sku?: T;
  featured?: T;
  status?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?:
    | T
    | {
        email?: T;
        firstName?: T;
        lastName?: T;
        phone?: T;
      };
  shippingAddress?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zipCode?: T;
        country?: T;
      };
  billingAddress?:
    | T
    | {
        sameAsShipping?: T;
        street?: T;
        city?: T;
        state?: T;
        zipCode?: T;
        country?: T;
      };
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        price?: T;
        total?: T;
        id?: T;
      };
  subtotal?: T;
  coupon?:
    | T
    | {
        code?: T;
        discountType?: T;
        discountValue?: T;
        discountAmount?: T;
      };
  shipping?: T;
  tax?: T;
  total?: T;
  status?: T;
  paymentStatus?: T;
  paymentMethod?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  description?: T;
  discountType?: T;
  discountValue?: T;
  minimumPurchase?: T;
  usageLimit?: T;
  usageCount?: T;
  validFrom?: T;
  validUntil?: T;
  active?: T;
  showOnSite?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Website name
   */
  siteName: string;
  /**
   * General site description
   */
  siteDescription: string;
  /**
   * Full site URL (without trailing /)
   */
  siteUrl: string;
  /**
   * Main contact email
   */
  contactEmail?: string | null;
  /**
   * Contact phone
   */
  contactPhone?: string | null;
  /**
   * Main site logo (recommended: PNG with transparent background)
   */
  logo: number | Media;
  /**
   * Logo for dark mode (optional)
   */
  logoDark?: (number | null) | Media;
  /**
   * Site favicon (recommended: ICO, PNG or SVG, 32x32px or larger)
   */
  favicon: number | Media;
  /**
   * Icon for Apple devices (recommended: PNG 180x180px)
   */
  appleTouchIcon?: (number | null) | Media;
  /**
   * Default SEO title (if empty, uses siteName)
   */
  metaTitle?: string | null;
  /**
   * Default SEO description (max. 160 characters)
   */
  metaDescription?: string | null;
  /**
   * Keywords separated by commas
   */
  metaKeywords?: string | null;
  /**
   * Site author
   */
  metaAuthor?: string | null;
  /**
   * Title for social media (if empty, uses metaTitle or siteName)
   */
  ogTitle?: string | null;
  /**
   * Description for social media
   */
  ogDescription?: string | null;
  /**
   * Image for sharing on social media (recommended: 1200x630px)
   */
  ogImage?: (number | null) | Media;
  /**
   * Open Graph content type
   */
  ogType?: ('website' | 'article' | 'product') | null;
  /**
   * Twitter/X card type
   */
  twitterCard?: ('summary' | 'summary_large_image' | 'app' | 'player') | null;
  /**
   * Twitter/X username (e.g.: @davincistore)
   */
  twitterHandle?: string | null;
  /**
   * Google Analytics Measurement ID (ej: G-XXXXXXXXXX)
   */
  googleAnalyticsId?: string | null;
  /**
   * Google Tag Manager ID (ej: GTM-XXXXXXX)
   */
  googleTagManagerId?: string | null;
  /**
   * Facebook Pixel ID
   */
  facebookPixelId?: string | null;
  /**
   * Google Search Console verification code
   */
  googleSiteVerification?: string | null;
  /**
   * Organization name for Schema.org
   */
  organizationName?: string | null;
  /**
   * Organization logo (will be used for JSON-LD)
   */
  organizationLogo?: (number | null) | Media;
  /**
   * Social media profiles for Schema.org
   */
  socialProfiles?:
    | {
        platform: 'facebook' | 'instagram' | 'twitter' | 'linkedin' | 'youtube' | 'tiktok';
        /**
         * Full profile URL
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  heroTitle: string;
  heroSubtitle?: string | null;
  heroMediaType: 'image' | 'video';
  /**
   * Background image for hero (recommended: 1920x1080px)
   */
  heroImage?: (number | null) | Media;
  /**
   * Background video for hero (format: MP4, WebM)
   */
  heroVideo?: (number | null) | Media;
  /**
   * Fallback image for devices that do not support video
   */
  heroVideoFallback?: (number | null) | Media;
  heroCTA?: {
    text?: string | null;
    link?: string | null;
  };
  videoSections?:
    | {
        title: string;
        description?: string | null;
        /**
         * Main video (MP4, WebM)
         */
        video: number | Media;
        /**
         * Video preview image
         */
        thumbnail?: (number | null) | Media;
        /**
         * External video URL (YouTube, Vimeo) - optional, if used the uploaded video is ignored
         */
        videoUrl?: string | null;
        layout?: ('full' | 'video-left' | 'video-right') | null;
        cta?: {
          text?: string | null;
          link?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  featuredProductsTitle?: string | null;
  featuredProductsSubtitle?: string | null;
  /**
   * Show featured products section (products marked as featured will be displayed automatically)
   */
  showFeaturedProducts?: boolean | null;
  /**
   * Number of featured products to display
   */
  featuredProductsLimit?: number | null;
  ctaSections?:
    | {
        title: string;
        description?: string | null;
        backgroundImage?: (number | null) | Media;
        /**
         * Background color in HEX format (e.g.: #000000) - used if there is no image
         */
        backgroundColor?: string | null;
        textColor?: ('dark' | 'light') | null;
        buttons?:
          | {
              text: string;
              link: string;
              variant?: ('default' | 'secondary' | 'outline') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  siteUrl?: T;
  contactEmail?: T;
  contactPhone?: T;
  logo?: T;
  logoDark?: T;
  favicon?: T;
  appleTouchIcon?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaKeywords?: T;
  metaAuthor?: T;
  ogTitle?: T;
  ogDescription?: T;
  ogImage?: T;
  ogType?: T;
  twitterCard?: T;
  twitterHandle?: T;
  googleAnalyticsId?: T;
  googleTagManagerId?: T;
  facebookPixelId?: T;
  googleSiteVerification?: T;
  organizationName?: T;
  organizationLogo?: T;
  socialProfiles?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroMediaType?: T;
  heroImage?: T;
  heroVideo?: T;
  heroVideoFallback?: T;
  heroCTA?:
    | T
    | {
        text?: T;
        link?: T;
      };
  videoSections?:
    | T
    | {
        title?: T;
        description?: T;
        video?: T;
        thumbnail?: T;
        videoUrl?: T;
        layout?: T;
        cta?:
          | T
          | {
              text?: T;
              link?: T;
            };
        id?: T;
      };
  featuredProductsTitle?: T;
  featuredProductsSubtitle?: T;
  showFeaturedProducts?: T;
  featuredProductsLimit?: T;
  ctaSections?:
    | T
    | {
        title?: T;
        description?: T;
        backgroundImage?: T;
        backgroundColor?: T;
        textColor?: T;
        buttons?:
          | T
          | {
              text?: T;
              link?: T;
              variant?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}